### PR TITLE
postgresql-dev: correct paths

### PR DESCRIPTION
**Pull request by anarazel**

### CODE REVIEW

**Comment by dpage** [comment]
I'm not sure I understand why you're changing the name of the tarball here?

I'd also note the code you changed in the second hunk is me debugging, as this is action is a WIP.

**Comment by anarazel** [comment]
> I'm not sure I understand why you're changing the name of the tarball here?

Because there are later steps that rely on the name being postgresql-dev (Upload Source, Upload Binaries).  I don't particularly care what name is being used, I just wanted the recipe to not fail :)

> I'd also note the code you changed in the second hunk is me debugging, as this is action is a WIP.

I understand that - but i think archiving that is actually not a bad idea...

**Comment by dpage** [comment]
> > I'm not sure I understand why you're changing the name of the tarball here?
> 
> Because there are later steps that rely on the name being postgresql-dev (Upload Source, Upload Binaries). I don't particularly care what name is being used, I just wanted the recipe to not fail :)

Ahh, right. That's a consequence of this being a WIP - I've been copy/pasting previous work, and then working through getting everything tweaked as necessary. Because I can only test this in Github, a lot of that has been single file edits in the GH UI. I suppose with you and Dave C looking at this now, I should really develop in my own dev repo.
 
> > I'd also note the code you changed in the second hunk is me debugging, as this is action is a WIP.
> 
> I understand that - but i think archiving that is actually not a bad idea...

Makes sense.

**Comment by anarazel** [comment]
Thanks.

**Pull request merged**
